### ISSUE TITLE
Issues with dependencies

### ISSUE THREAD

**Issue by imvladikon** [amir-zeldes/RFTokenizer#12]
Hi Amir,
Thank you for your impressive work!

But it seems that some of the dependencies are not fixed and checkpoints that were saved under old versions, could not be deserialized:

**What was done:**
```pip install git+https://github.com/amir-zeldes/RFTokenizer```
or
```
pip install rftokenizer
```

```python
from rftokenizer import RFTokenizer

rf_tok = RFTokenizer(model="heb")

data = """אני רוצה לקנות חלב וגבינה."""

tokenized = rf_tok.rf_tokenize(data.strip().split())
print(tokenized)

```

**What was gotten:**
For env1: local PC (ubuntu), transformers >=4.3.0, "ModuleNotFoundError: No module named 'transformers.modeling_bert'"
For env2: colab (AttributeError: module 'collections' has no attribute 'Mapping') -> xgboost version problem

**What could be done**
for first case, it's possible to eliminate problems with fixed versions:
```
 torch==1.9.1
```
because `torch>=2` will raise exceptions for old transformers -
```
Transformer: Error importing packages. ImportError: cannot import name SAVE_STATE_WARNING from torch.optim.lr_scheduler
```

```protobuf==3.20.1```  - to prevent breaking changes in protobuf 4 (in the old transformers, it raises an exception)

and transformers should be less version `4` for having `transformers.modeling_bert'`
```
transformers==3.5.1
```

_PS. but unfortunately fixed versions is not good solution. (so, maybe it's possible to update checkpoints according to new versions)_

**Comment by amir-zeldes** [comment]
Yeah, I see the issue. This puts me in a bit of a dilemma, since we are not a software development company and don't really have the resources to keep up with each change in library versions... That said, I would be sad to see this tool become obsolete, so maybe we can occasionally retrain models.

OK, so two answers for now:

1. If you want to test this right now, and are willing to run some older libraries in a venv or something, here is a known working configuration for the models you have from the download:

Python 3.8:
```
scikit-learn==0.23.2
joblib==1.3.2
numpy==1.21.0
pandas==1.5.3
xgboost==0.81
hyperopt==0.2.4
flair==0.6.1
```

2. I will try to put up a model for a newer python, say 3.11, with torch > 2.0 and the latest transformers + xgboost (not promising to do this for every major version, but it's been a while so at least for now I'll make new models)

**Comment by imvladikon** [comment]
>If you want to test this right now, and are willing to run some older libraries in a venv or something, here is a known working configuration for the models you have from the download:

yeap, this is what I did, to check it. and it works.


>Yeah, I see the issue. This puts me in a bit of a dilemma, since we are not a software development company 
I understand, I was thinking just about using RFTokenizer in our IAHLT spacy pipeline as additional dependency (and such pipe should work under different settings and dependencies)

as I assume, maybe it's better if I will use just specific parts of the pipeline (models) and put them into iahlt spacy pipe(with reference to `RFTokenizer`)? the final goal is using it as segmentizer/tokenizer in pipeline, to get Hebrew spacy pipeline (with dependency parsing, NER, etc., things. which will be possible to install using just `pip install hespacy`)

**Comment by amir-zeldes** [comment]
OK, I now have up-to-date Hebrew models for RFTokenzier here:

https://gucorpling.org/amir/download/heb_models_v4/

If you pull the dev branch and use torch 2.1, xgboost 2.0.2 and flair 0.13.0, these models should work - let me know otherwise. 

Before making this just pip installable, I would still need to implement some automatic checks for which model version to download on a fresh install, and I'd need to also update models for other languages to match. Once that's done, the rest of hebpipe could be updated. At that point you wouldn't need to use spacy unless you need for some other reasons.

**Comment by amir-zeldes** [comment]
OK, this should work now under rftokenizer V2.2.0, but please test and let me know if you encounter any issues. HebPipe is next...

**Comment by imvladikon** [comment]
Hi Amir,

Thank you very much!
I will check a new version soon , and definitely let you know,🙏
PS. I close the issue, - if I find something, I'll just reopen it. thank you, again!

**Comment by ZvikaZ** [comment]
Hi.
I've tried using the latest release, and encountered versions problems again.

Can you please write which Python version are you using, and the output of `pip list`, so I could overcome this?

Thanks

**Comment by amir-zeldes** [comment]
It sounds like everything is working based on #14 - let me know if you still run into any issues
